"""empty message

Revision ID: 229f698703f5
Revises: af8e7eec98ca
Create Date: 2016-08-08 18:07:54.272666

"""

# revision identifiers, used by Alembic.
revision = '229f698703f5'
down_revision = 'af8e7eec98ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ass')
    op.drop_table('ass')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following')
    op.drop_table('following')
    ### end Alembic commands ###
