"""empty message

Revision ID: 7cecb0bfa5da
Revises: f864c13ef246
Create Date: 2016-08-07 21:34:17.998872

"""

# revision identifiers, used by Alembic.
revision = '7cecb0bfa5da'
down_revision = 'f864c13ef246'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
