"""empty message

Revision ID: 86f74995fc6e
Revises: d8f096c4ff75
Create Date: 2016-08-08 22:20:01.669378

"""

# revision identifiers, used by Alembic.
revision = '86f74995fc6e'
down_revision = 'd8f096c4ff75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    ### end Alembic commands ###
