"""empty message

Revision ID: d8f096c4ff75
Revises: eae9359e6138
Create Date: 2016-08-08 21:13:22.949391

"""

# revision identifiers, used by Alembic.
revision = 'd8f096c4ff75'
down_revision = 'eae9359e6138'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balls')
    op.drop_table('balls')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('following', sa.Column('follow_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('following', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.drop_constraint(None, 'following', type_='foreignkey')
    op.create_foreign_key('following_follow_user_fkey', 'following', 'users', ['follow_user'], ['id'])
    op.create_foreign_key('following_user_fkey', 'following', 'users', ['user'], ['id'])
    op.drop_column('following', 'user_id')
    op.drop_column('following', 'following_id')
    ### end Alembic commands ###
