"""empty message

Revision ID: eae9359e6138
Revises: 229f698703f5
Create Date: 2016-08-08 18:09:03.626669

"""

# revision identifiers, used by Alembic.
revision = 'eae9359e6138'
down_revision = '229f698703f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crap')
    op.drop_table('crap')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following')
    op.drop_table('following')
    ### end Alembic commands ###
